/*insert into VEHICLE_TYPE ( ID, TYPE, REGISTRATION_STATUS, REGISTRATION_DATE )
values( NEXTVAL('VEHICLETYPE_SEQ'),'MOTOCICLETA', '0', CURRENT_TIMESTAMP );
insert into VEHICLE_TYPE ( ID, TYPE, REGISTRATION_STATUS, REGISTRATION_DATE )
values( NEXTVAL('VEHICLETYPE_SEQ'),'AUTOMOVIL', '0', CURRENT_TIMESTAMP );

insert into VEHICLE ( ID, PLATE, TYPE, REGISTRATION_STATUS, REGISTRATION_DATE )
values( NEXTVAL('VEHICLE_SEQ'),'HSD11A', 1, '0', CURRENT_TIMESTAMP );
insert into VEHICLE ( ID, PLATE, TYPE, REGISTRATION_STATUS, REGISTRATION_DATE )
values( NEXTVAL('VEHICLE_SEQ'),'HSD12A', 1, '0', CURRENT_TIMESTAMP );*/